### ISSUE TITLE
One of the pkgs does not exist and causing the build to fail

### ISSUE THREAD

**Issue by ohadm2** [microsoft/CBL-MarinerDemo#11]
Hi.

After running the command **sudo make iso CONFIG_FILE=../imageconfigs/demo_iso.json**
I'm getting a 404 not found error for one of the pkgs.

Trying to get the pkg via browser confirms that it does not exist.

Full error from terminal:

ERROR: Failed to download toolchain package: gdbm-debuginfo-1.18-3.cm1.x86_64.rpm.
ERROR: Last 20 lines from log '/home/ohadm/CBL-MarinerDemo/build/logs/toolchain/downloads/gdbm-debuginfo-1.18-3.cm1.x86_64.rpm.log':

	Downloading toolchain RPM: gdbm-debuginfo-1.18-3.cm1.x86_64.rpm
	--2021-07-21 03:36:35--  https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms/gdbm-debuginfo-1.18-3.cm1.x86_64.rpm
	Resolving packages.microsoft.com (packages.microsoft.com)... failed: Temporary failure in name resolution.
	wget: unable to resolve host address ‘packages.microsoft.com’
	--2021-07-21 03:36:45--  https://packages.microsoft.com/cbl-mariner/1.0/prod/update/x86_64/rpms/gdbm-debuginfo-1.18-3.cm1.x86_64.rpm
	Resolving packages.microsoft.com (packages.microsoft.com)... 104.214.230.139
	Connecting to packages.microsoft.com (packages.microsoft.com)|104.214.230.139|:443... connected.
	HTTP request sent, awaiting response... 404 Not Found
	2021-07-21 03:36:46 ERROR 404: Not Found.
	
 Toolchain download failed. See above errors for more details.

Also pic included.

Regards,

![cbl-mariner-404-err](https://user-images.githubusercontent.com/13061670/126637692-12761f9a-8d9f-46bd-b495-017d419bece6.PNG)

**Comment by jslobodzian** [comment]
This was likely a temporary glitch as this issue has not been seen for awhile.  Closing as not reproducible.
