### ISSUE TITLE
The FTP link doesn't render in the formatted markdown README file.

### ISSUE THREAD

**Issue by thalesx** [microsoft/CBL-MarinerDemo#17]
https://github.com/microsoft/CBL-MarinerDemo/blob/001337e5fc2ad4b85e616b5121b4469f77794199/README.md?plain=1#L382

In the formatted markdown file the FTP link to the gnuchess tarball source shows up as a plain "here" text, no hyperlink, which is confusing to the reader. It looks like github's markdown formatter doesn't support FTP links. Perhaps the README could reference the HTTPS link (https://ftp.gnu.org/gnu/chess/)

**Comment by jslobodzian** [comment]
Should be fixed now.
