### ISSUE TITLE
Cannot establish SSH connection to CBL-Mariner OS

### ISSUE THREAD

**Issue by proy1234** [microsoft/CBL-MarinerDemo#6]
I have installed the CBL-Mariner on my laptop and trying to SSH to the same from the laptop console. The host got the ECDSA key fingerprint but after that, it asks me to enter the password. It looks like the received public key is not matching with the stored version at the host. Any assistance you can provide would be greatly appreciated. Please find the log below.

ssh -v root@172.31.88.10

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Connecting to 172.31.88.105 [172.31.88.105] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_ed25519-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_xmss type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\v-praraju/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.5
debug1: match: OpenSSH_8.5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 172.31.88.105:22 as 'root'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:bxV9a9vziCDEPZjonFKT3WByUxPc+HIql3hrvceQvA8
debug1: read_passphrase: can't open /dev/tty: No such file or directory
The authenticity of host '172.31.88.105 (172.31.88.105)' can't be established.
ECDSA key fingerprint is SHA256:bxV9a9vziCDEPZjonFKT3WByUxPc+HIql3hrvceQvA8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.31.88.105' (ECDSA) to the list of known hosts.
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey

debug1: Next authentication method: keyboard-interactive
debug1: read_passphrase: can't open /dev/tty: No such file or directory
Password:

**Comment by PawelWMS** [comment]
Hi Prasad,

We can confirm that SSH key authentication works for Mariner in general, so I'd double-check the host's SSH server configuration:

1. Is public key authentication enabled inside the SSH server's config file (`/etc/ssh/sshd_config`).
2. Is your **public** key placed inside `~/.ssh/authorized_keys` on the Mariner system and you're connecting to the machine using the key's **private** counterpart.

For more information, please refer to the [public documentation for SSH](https://www.ssh.com/academy/ssh/public-key-authentication).

**Comment by proy1234** [comment]
Thanks, Pawel. This information help to solve the problem

**Comment by PawelWMS** [comment]
Glad to help.
